package org.BookNBook.model;

public enum TematicaLibro {
    LITERARIA, NEGRA, HISTORICA, ROMANTICA, EROTICA, POESIA, TEATRO, CIENCIAFICCION, TERROR, FANTASIA, COMIC, CIENCIA, ARTE, PSICOLOGIA, FILOSOFIA, RELIGION, DICCIONARIO, EDUCACION, SALUD, COCINA, HUMOR, OCIO
}
